version: "3.8"
services:
  nestjs-api:
    image: phatpt08/nestjs-api
    container_name: 'hunet'
    ports:
      - 3000:3000
    depends_on:
      - mysql
    
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'hunet'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    name: hunet-db

  #mysql -u root -p
  #ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '123456';  